# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "gradle"
      rebase-strategy: "disabled"
      directory: "/"
      schedule:
          interval: "weekly"

      groups:
        major:
          patterns:
            - "*"
          update-types:
            - "major"
        minor:
          patterns:
            - "*"
          update-types:
            - "minor"
        patch:
          patterns:
            - "*"
          update-types:
            - "patch"

    - package-ecosystem: "github-actions"
      rebase-strategy: "disabled"
      directory: "/"
      schedule:
          interval: "weekly"
